### ISSUE TITLE
Error in Decode -  Cannot decode EPC with header C3

### ISSUE THREAD

**Issue by mimansa-dev** [fulfilio/pyepc#10]
### Discussed in https://github.com/fulfilio/pyepc/discussions/9

<div type='discussions-op-text'>

<sup>Originally posted by **mimansa-dev** October  8, 2022</sup>
I am trying to decode a EPC but get an error "pyepc.exceptions.DecodingError: Cannot decode EPC with header C3"

```
from pyepc import decode
sgtin = decode('C310821E1A27B82D49F00003')
```

The traceback is as follows. Appreciate if someone could guide me.

```
Traceback (most recent call last):
  File "/opt/app/virtual/cinetopia/lib64/python3.6/site-packages/pyepc/epc.py", line 183, in decode
    header_class_map[header]
KeyError: 'C3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/app/virtual/cinetopia/lib64/python3.6/site-packages/pyepc/epc.py", line 186, in decode
    "Cannot decode EPC with header {}".format(header)
pyepc.exceptions.DecodingError: Cannot decode EPC with header C3

```</div>

**Comment by legomatrix** [comment]
"C310821E1A27B82D49F00003" is not a valid GS1 EPC. Please check if your EPC decodes via https://www.gs1.org/services/epc-encoderdecoder, if it decodes, it should decode fine with Pyepc also.
